In [8]:
import numpy as np
import pandas as pd
from numpy import random

Statistics -part of mathematics


**Types of statistics- (Branches of statistics)**
1. Descriptive -> provides summarisation and visualisation
    - frequency tables
    - Mean,median,mode,std,variance
    - charts
2. Inferential -> inference, here we decide whether any predictor/s variable/s(input variable) influence the response(output) 
    - Inference/ conclusion.
3. Predictive -> prediction of future data based on truthful historical data(reliable).
   - Historical value -> Future value 


In [5]:
grades=np.repeat(['A','B','C','D'],[10,5,7,3])
grades

array(['A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'A', 'B', 'B', 'B',
       'B', 'B', 'C', 'C', 'C', 'C', 'C', 'C', 'C', 'D', 'D', 'D'],
      dtype='<U1')

In [10]:
np.random.shuffle(grades)

In [11]:
grades

array(['A', 'C', 'C', 'C', 'A', 'A', 'A', 'C', 'B', 'B', 'C', 'A', 'B',
       'A', 'D', 'D', 'D', 'A', 'B', 'C', 'A', 'A', 'A', 'B', 'C'],
      dtype='<U1')

In [18]:
len(grades)

25

In [20]:
np.unique(grades)

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [25]:
grade_count=np.unique(grades,return_counts=True)
grade_count

(array(['A', 'B', 'C', 'D'], dtype='<U1'), array([10,  5,  7,  3]))

In [26]:
grade_count[0]

array(['A', 'B', 'C', 'D'], dtype='<U1')

In [30]:
grade_proportion=grade_count[1]/len(grades)
grade_proportion

array([0.4 , 0.2 , 0.28, 0.12])

In [33]:
grade_percentage=grade_proportion*100
grade_percentage

array([40., 20., 28., 12.])

In [34]:
grade_proportion.cumsum()

array([0.4 , 0.6 , 0.88, 1.  ])

In [35]:
np.cumsum(grade_proportion)

array([0.4 , 0.6 , 0.88, 1.  ])

In [38]:
np.round(grade_proportion,1)

array([0.4, 0.2, 0.3, 0.1])

In [41]:
# np.sort(grade_proportion,reverse=True)
sorted(grade_proportion,reverse=True)

[np.float64(0.4), np.float64(0.28), np.float64(0.2), np.float64(0.12)]

In [55]:
np.sort(-grade_proportion)


array([-0.4 , -0.28, -0.2 , -0.12])

In [47]:
np.flip(grade_proportion)

array([0.12, 0.28, 0.2 , 0.4 ])

In [48]:
grade_count

(array(['A', 'B', 'C', 'D'], dtype='<U1'), array([10,  5,  7,  3]))

In [50]:
np.argsort(grade_count[1])   #gives index value of values in the array from the index of the lowest value to the index of the highest value.

array([3, 1, 2, 0])

In [57]:
np.argsort(-grade_count[1])  #same as above but reverse

array([0, 2, 1, 3])

In [58]:
# 1. Measures of central tendency -> Mean,median,mode
# 2. Measure of dispersion
# 3.

**Mean should be calculated only when-**
1. Data is symmetric
2. Data does not have any extreme values, especially only on one side.

In [60]:
# example-
sal=np.array([6,7,6,7,8,7,6,7,8,8,8,6,7,6,7])

In [65]:
np.mean(sal)

np.float64(6.933333333333334)

In [64]:
np.median(sal)

np.float64(7.0)

In [66]:
# But if salary has some students who got placed abroad having very high packages-60,70,80,65 then mean will give a bad
# value and median will be more helpful in such a case.

In [72]:
# As in this example-
new_sal=np.array([6,7,6,7,8,7,6,7,8,8,8,6,7,6,7,65,70,80,65])

In [73]:
np.mean(new_sal)

np.float64(20.210526315789473)

In [74]:
np.median(new_sal)

np.float64(7.0)