In [56]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from numpy import random

import scipy
from scipy import stats
from scipy.stats import binom,poisson,norm,t

import pylab
from pylab import legend, plot, show ,title, xlabel, ylabel

import statsmodels
from statsmodels import stats
from statsmodels.stats import weightstats as ssw

import statsmodels.api as sm
from statsmodels.formula.api import ols
import statsmodels.stats.multicomp

from statsmodels.stats import proportion as ssp

from scipy.stats import chisquare, chi2_contingency

In [2]:
# Ho: prop of exp students<=0.1

In [3]:
# Ha: prop of exp students>0.1

In [4]:
# In a sample of 30 students , 5 students had work experience. Isthe sample in sync with Vineeta Maams claim?


In [5]:
ssp.proportions_ztest(5,30,0.1,alternative='larger')

(np.float64(0.979795897113271), np.float64(0.16359343889515293))

In [6]:
#Since the p-value is more than the LOS we do not reject the null hypothesis.

In [7]:
#My claim is that minimum 30% of the people in kharghar are graduates. In a sample of 200 people, 50 were found to be grads.
#Does the sample support the claim.

##### 

In [8]:
50/200

0.25

In [13]:
ssp.proportions_ztest(50,200,.3,alternative='smaller')

(np.float64(-1.6329931618554518), np.float64(0.051235217429874705))

In [14]:
# ho-    >=30
#ha      <30

In [12]:
# p-value>0.05 so we do not reject Ho

In [15]:
#Lower bound at 95% conf level

In [22]:
norm.ppf(0.05)

np.float64(-1.6448536269514729)

In [23]:
norm.ppf(0.051235217429874705)

np.float64(-1.6329931618554525)

In [18]:
# sd of proportion= (proportion * 1-proportion)**0.5

In [19]:
# lb=0.25-(1.6448536269514729*(0.3*0.7)**0.5/200**.5)
# lb

0.19670065078445906

In [25]:
ub=0.25+(1.6448536269514729*(0.3*0.7)**0.5/200**.5)
ub   #Here we calculate upper bound because our error is on the left side

0.30329934921554097

# Two Sample proportion test

In [32]:
# Ho: prop(mum)-prop(blor)<=.15   Ha: prop(mum)-prop(blore)>.15

In [33]:
# in mumbai, in a sample of 150 people, 60 were grads

In [34]:

#in blore, in a sample of 180 people , 40 were grads

In [35]:
60/150-40/180

0.1777777777777778

In [36]:
ssp.proportions_ztest(np.array([60,40]),np.array([150,180]),.15,alternative='larger')

(np.float64(0.5467294060851874), np.float64(0.29228232428556866))

In [38]:
# p-value = 0.2922 > 0.05 , so we do not reject Ho.

In [42]:
40/180-60/150  #(blore-mum)

-0.1777777777777778

In [43]:
ssp.proportions_ztest(np.array([40,60]),np.array([180,150]),.15,alternative='larger')

(np.float64(-6.451406991805203), np.float64(0.9999999999445918))

In [44]:
pbar=(60+40)/(150+180)
pbar

0.30303030303030304

In [45]:
qbar=(1-pbar)

In [46]:
qbar

0.696969696969697

In [48]:
Nr=60/150-40/180-0.15

In [49]:
Dr=(pbar*qbar*(1/150+1/180))**0.5

In [50]:
Nr/Dr

0.5467294060851874

In [51]:
norm.sf(Nr/Dr)

np.float64(0.29228232428556866)

In [52]:
norm.sf(1.7)

np.float64(0.04456546275854304)

In [54]:
0.17777777777-1.645*Dr  #Lower bound

0.09419997138926046

In [55]:
ssp.proportions_ztest(np.array([60,40]),np.array([150,180]),0.093,alternative='larger')

(np.float64(1.66861814737199), np.float64(0.047596540033846606))

# Chi Square Test
- for goodness of fit.

In [ ]:
# Expected mkt share of different colours of a car

Ho: count follow the pattern(of expected market share) <br>
Ha: count do not follow the pattern

In [72]:
exp_mkt_share=np.array([0.45,0.3,.2,.05])   #given

In [59]:
obs_counts=np.array([400,350,150,100])

In [69]:
obs_mkt_share=obs_counts/sum(obs_counts)
obs_mkt_share  #obs prop share

array([0.4 , 0.35, 0.15, 0.1 ])

In [70]:
#if the difference between expected and observed market share significant or not is determined by chi square test


In [68]:
exp_counts=exp_mkt_share*sum(obs_counts)
exp_counts

array([450., 300., 200.,  50.])

In [74]:
scipy.stats.chisquare(obs_counts,f_exp=exp_counts)   #chidist formula in excel for p-value

Power_divergenceResult(statistic=np.float64(76.38888888888889), pvalue=np.float64(1.82556103097206e-16))

In [73]:
#we reject the null hypothesis

test statistic value=summation of ((O-E)**2/E)

# Chi square test for Degree of Association

In [81]:
# NorthInd,Southind,Chinese

In [77]:
males=[20,30,10]
females=[15,20,30]
food_data=np.array([males,females])
food_data

array([[20, 30, 10],
       [15, 20, 30]])

In [80]:
scipy.stats.chi2_contingency(food_data)  #it results into a contingency table

Chi2ContingencyResult(statistic=np.float64(12.534340659340657), pvalue=np.float64(0.0018975905490087818), dof=2, expected_freq=array([[16.8, 24. , 19.2],
       [18.2, 26. , 20.8]]))

In [79]:
# ddof=(row-1)*(column-1)

In [82]:
#Ho : no association between gender and type of cuisine
#Ho : there is an association

In [83]:
#Contingency table in exams # imp - very repeated question
#fill in the missing values in the contingency table