In [2]:
import numpy as np
from numpy import random

In [3]:
# 1. Write a NumPy program to find the dot product of two arrays of different dimensions.


In [4]:
# 2. Write a NumPy program to create a 3x3 identity matrix and stack it vertically and horizontally.
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [5]:
# 3. Write a NumPy program to create a 4x4 array with random values and find the sum of each row.
a=np.arange(16).reshape(4,4)
sm=np.sum(a,axis=1)
print('The 4x4 array is-')
print(a)
print()
print('Sum of -')
for i in range(len(sm)):
    print(f'Row {i}:',sm[i])


The 4x4 array is-
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Sum of -
Row 0: 6
Row 1: 22
Row 2: 38
Row 3: 54


In [6]:
# 4. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each row from each element.
a=np.arange(9).reshape(3,3)
print('The 3x3 array is-')
print(a)
print()
for i in a:
    print(i-np.mean(i))

The 3x3 array is-
[[0 1 2]
 [3 4 5]
 [6 7 8]]

[-1.  0.  1.]
[-1.  0.  1.]
[-1.  0.  1.]


In [7]:
# 5. Write a NumPy program to create a 3x3 array with random values and subtract the mean of each column from each element.
a=np.random.randint(1,100,9).reshape(3,3)
a=np.arange(9).reshape(3,3)
print(a)
print()
print(a-np.mean(a,axis=0).reshape(3,1))

[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[-3. -2. -1.]
 [-1.  0.  1.]
 [ 1.  2.  3.]]


In [8]:
np.mean(a,axis=0).reshape(3,1)

array([[3.],
       [4.],
       [5.]])

In [54]:
# 6. Write a NumPy program to create a 5x5 array with random values and normalize it row-wise.

# normalized value = value-mean(all values)/std deviation of all values)
# np.mean()
# np.std()

# a-(np.mean(a)/np.std(a))



array([[46.00029129, 57.00029129, 45.00029129, 26.00029129, 86.00029129],
       [67.00029129, 81.00029129, 11.00029129, 82.00029129, 30.00029129],
       [67.00029129, 68.00029129, 44.00029129, 55.00029129, 58.00029129],
       [79.00029129, 21.00029129, 14.00029129, 91.00029129, 53.00029129],
       [57.00029129,  2.00029129, 84.00029129, 23.00029129, 13.00029129]])

In [10]:
# 7. Write a NumPy program to create a 5x5 array with random values and normalize it column-wise.


In [30]:
# 8. Write a NumPy program to create a 3x3x3 array with random values and find the sum along the last axis.

a=np.arange(27).reshape(3,3,3)
print(a)
np.sum(a,axis=0)


[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]


array([[27, 30, 33],
       [36, 39, 42],
       [45, 48, 51]])

In [33]:
# 9. Write a NumPy program to create a 5x5 array with random values and sort each row.
a=np.random.randint(0,100,25).reshape(5,5)
print(a)
print('Sorted-')

np.sort(a,axis=1)


[[42 48  9 24 93]
 [77 87 18 97 83]
 [58 42 45 76 71]
 [33 20 62 32 70]
 [12 55 18  5 46]]
Sorted-


array([[ 9, 24, 42, 48, 93],
       [18, 77, 83, 87, 97],
       [42, 45, 58, 71, 76],
       [20, 32, 33, 62, 70],
       [ 5, 12, 18, 46, 55]], dtype=int32)

In [35]:
# 10. Write a NumPy program to create a 5x5 array with random values and sort each column.
a=random.randint(1,100,25).reshape(5,5)
print(a)
np.sort(a,axis=0)

[[38 17 70 39 56]
 [52 50 22 57 89]
 [ 2 87 64 76 59]
 [54 73 67 51 57]
 [68 49 15 21 47]]


array([[ 2, 17, 15, 21, 47],
       [38, 49, 22, 39, 56],
       [52, 50, 64, 51, 57],
       [54, 73, 67, 57, 59],
       [68, 87, 70, 76, 89]], dtype=int32)

In [ ]:
np.random.randint(1,15)

In [55]:
# 11. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each row.
a=random.randint(1,100,25).reshape(5,5)
print(a)
print(np.sort(a,axis=1))
print(np.sort(a,axis=1)[:,3])  #wrong one

np.sort(a,axis=1)[:,-2]  #correct one



[[16 59 28 81 97]
 [ 9 94 44 64 72]
 [88  5 11 23 42]
 [95  1 62 66 60]
 [ 5 95 48 50 59]]
[[16 28 59 81 97]
 [ 9 44 64 72 94]
 [ 5 11 23 42 88]
 [ 1 60 62 66 95]
 [ 5 48 50 59 95]]
[81 72 42 66 59]


array([81, 72, 42, 66, 59], dtype=int32)

In [56]:
# 12. Write a NumPy program to create a 5x5 array with random values and find the second-largest value in each column.
a=random.randint(1,100,25).reshape(5,5)
print(a)
print(np.sort(a,axis=0))
np.sort(a,axis=0)[-2,:]

[[61 64 58 47 37]
 [54 49 63 63 49]
 [33 34 79 89 64]
 [57 54 72 64 84]
 [60 98 15 70  1]]
[[33 34 15 47  1]
 [54 49 58 63 37]
 [57 54 63 64 49]
 [60 64 72 70 64]
 [61 98 79 89 84]]


array([60, 64, 72, 70, 64], dtype=int32)

In [48]:
# 13. Write a NumPy program to create a 5x5 array with random values and replace the maximum value with 0.
a=random.randint(1,100,25).reshape(5,5)
print(a)
print(a.max())
a[np.where(a==a.max())]=0
print(a)

[[56 21 72 53 60]
 [38  9 26 41 64]
 [57  9 14 87 87]
 [ 5  3 81 85 84]
 [58 44 63 23 91]]
91
[[56 21 72 53 60]
 [38  9 26 41 64]
 [57  9 14 87 87]
 [ 5  3 81 85 84]
 [58 44 63 23  0]]


In [49]:
# 14. Write a NumPy program to create a 5x5 array with random values and replace the minimum value with 0.
a=random.randint(1,100,25).reshape(5,5)
print(a)
print(a.min())
a[np.where(a==a.min())]=0
print(a)


[[50 12 18 81 54]
 [47  9 40 26  7]
 [19 31  6 51  2]
 [76 70  9 18  3]
 [68 82 29 11 89]]
2
[[50 12 18 81 54]
 [47  9 40 26  7]
 [19 31  6 51  0]
 [76 70  9 18  3]
 [68 82 29 11 89]]


In [3]:
# 15. Write a NumPy program to create a 5x5 array with random values and calculate the exponential of each element.
a=random.randint(1,100,25).reshape(5,5)
a**2
a

array([[10, 60, 42, 65, 67],
       [66,  5, 52, 51, 75],
       [85, 32, 81, 34, 47],
       [56, 64,  8,  9,  5],
       [94,  7, 70, 33, 75]], dtype=int32)

In [5]:
# 1. Write a Python program to find the maximum and minimum value of a given flattened array.
# Expected Output:
# Original flattened array:
# [[0 1]
# [2 3]]
# Maximum value of the above flattened array:
# 3
# Minimum value of the above flattened array:
# 0

a.max()

np.int32(94)

In [58]:
# 2. Write a NumPy program to get the minimum and maximum value of a given array along the second axis.
# Expected Output:
# Original array:
# [[0 1]
# [2 3]]
# Maximum value along the second axis:
# [1 3]
# Minimum value along the second axis:
# [0 2]
a=[[0,1],[2,3]]
np.sort(a,axis=0)

array([[0, 1],
       [2, 3]])

In [ ]:
# 3. Write a NumPy program to calculate the difference between the maximum and the minimum values of a given array along the second axis.
# Expected Output:
# Original array:
# [[ 0 1 2 3 4 5]
# [ 6 7 8 9 10 11]]
# Difference between the maximum and the minimum values of the said array:
# [5 5]




In [ ]:
# 4. Write a NumPy program to compute the 80th percentile for all elements in a given array along the second axis.
# Expected Output:
# Original array:
# [1.0, 2.0, 3.0, 4.0]
# Largest integer smaller or equal to the division of the inputs:
# [ 0. 1. 2. 2.]



In [ ]:
# 5. Write a NumPy program to compute the median of flattened given array.
# Note: First array elements raised to powers from second array
# Expected Output:
# Original array:
# [[ 0 1 2 3 4 5]
# [ 6 7 8 9 10 11]]
# Median of said array:
# 5.5

In [ ]:
# 6. Write a NumPy program to compute the weighted of a given array.
# Sample Output:
# Original array:
# [0 1 2 3 4]
# Weighted average of the said array:
# 2.6666666666666665

In [ ]:
# 7. Write a NumPy program to compute the mean, standard deviation, and variance of a given array along the second axis.
# Sample output:
# Original array:
# [0 1 2 3 4 5]
# Mean: 2.5
# std: 1
# variance: 2.9166666666666665



In [ ]:
# 8. Write a NumPy program to compute the covariance matrix of two given arrays.
# Sample Output:
# Original array1:
# [0 1 2]
# Original array1:
# [2 1 0]
# Covariance matrix of the said arrays:
# [[ 1. -1.]
# [-1. 1.]]



In [ ]:
# 9. Write a NumPy program to compute cross-correlation of two given arrays.
# Sample Output:
# Original array1:
# [0 1 3]
# Original array1:
# [2 4 5]
# Cross-correlation of the said arrays:
# [19]

In [ ]:
# 10. Write a NumPy program to compute pearson product-moment correlation coefficients of two given arrays.
# Sample Output:
# Original array1:
# [0 1 3]
# Original array1:
# [2 4 5]
# Pearson product-moment correlation coefficients of the said arrays:
# [[1. 0.92857143]
# [0.92857143 1. ]]

In [ ]:
# 11. Write a NumPy program to test element-wise of a given array for finiteness (not infinity or not Not a Number), positive or negative infinity, for NaN, for NaT (not a time), for negative infinity, for positive infinity.
# Sample output:
# Test element-wise for finiteness (not infinity or not Not a Number):
# True
# True
# False
# Test element-wise for positive or negative infinity:
# True
# False
# True
# Test element-wise for NaN:
# [ True False False]
# Test element-wise for NaT (not a time):
# [ True False]
# Test element-wise for negative infinity:
# [1 0 0]
# Test element-wise for positive infinity:
# [0 0 1]

In [ ]:
# 12. Write a Python NumPy program to compute the weighted average along the specified axis of a given flattened array.
# From Wikipedia: The weighted arithmetic mean is similar to an ordinary arithmetic mean (the most common type of average), except that instead of each of the data points contributing equally to the final average, some data points contribute more than others. The notion of weighted mean plays a role in descriptive statistics and also occurs in a more general form in several other areas of mathematics.
# Sample output:
# Original flattened array:
# [[0 1 2]
# [3 4 5]
# [6 7 8]]
# Weighted average along the specified axis of the above flattened array:
# [1.2 4.2 7.2]

In [ ]:
# 13. Write a Python program to count number of occurrences of each value in a given array of non-negative integers.
# Note: bincount() function count number of occurrences of each value in an array of non-negative integers in the range of the array between the minimum and maximum values including the values that did not occur.
# Sample Output:
# Original array:
# [0, 1, 6, 1, 4, 1, 2, 2, 7]
# Number of occurrences of each value in array:
# [1 3 2 0 1 0 1 1]

In [ ]:
# 14. Write a NumPy program to compute the histogram of nums against the bins.
# Sample Output:
# nums: [0.5 0.7 1. 1.2 1.3 2.1]
# bins: [0 1 2 3]
# Result: (array([2, 3, 1], dtype=int64), array([0, 1, 2, 3]))